# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mydebian"
  config.vm.hostname = "mydeb"
  config.vm.network "private_network", ip:"192.168.56.3"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.cpus = "1"
    # Customize the amount of memory on the VM:
    vb.memory = "768"
  end

end
