# -*- mode: ruby -*-
# vi: set ft=ruby :
RAM = 512
CPU = 1

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"
  config.vm.hostname = "myos"
  config.vm.network "private_network", ip:"192.168.56.30"

  config.vm.provider "vitualbox" do |vb|
    vb.memory = RAM
    vb.cpus = CPU
  end

end
